### ISSUE TITLE
rss-ladder issues in Ubuntu 12.04 and 16.04

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [strizhechenko/netutils-linux#98]
Probably connected with #91 

**Ubuntu 12.04**
```
TERM=screen-bce
LANG=en_US.UTF-8
LANGUAGE=en_US:en
```
```
# rss-ladder eth1 0
- distribute interrupts of eth1 (-rx-) on socket 0
lscpu: unrecognized option '--extended=CPU,SOCKET'
```

**Ubuntu 16.04.2**
```
TERM=xterm (xfce-terminal)
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU:ru:en
```
```
# rss-ladder eth1 0
- distribute interrupts of eth1 (-rx-) on socket 0
  - eth1: irq 128 1572865-edge -> eth1-rx-0
/usr/local/bin/rss-ladder: строка 80: echo: ошибка записи: Недопустимый аргумент
```

----
- [x] 12.04
- [ ] 16.04

**Comment by strizhechenko** [comment]
Hello!

12.04 issue is fixed in 2.0.5 version: https://github.com/strizhechenko/netutils-linux/issues/96

**Comment by sergey-dryabzhinsky** [comment]
Something wrong with number of cpu cores detection:
```
# rss-ladder eth1 0
- distribute interrupts of eth1 (-rx-) on socket 0
  - eth1: irq 46 eth1-rx-0 -> 0
- distribute interrupts of eth1 (-tx-) on socket 0
  - eth1: irq 47 eth1-tx-0 -> 0

# grep -P 'cores|siblings' /proc/cpuinfo | sort -u
cpu cores       : 2
siblings        : 2
```

Or network cart / driver not capable?

**Comment by strizhechenko** [comment]
This problem is described here:
https://github.com/strizhechenko/netutils-linux/issues/8

Your network card is capable, but this is beyond rss-ladder's duty I think.

Also, I just got an interesting idea. If you have router with 2 similar network cards, you can bind queues to cpus this way:

eth1-rx - cpu0
eth1-tx - cpu1
ethX-rx - cpu1
ethX-tx - cpu0

It should increase the cache hit rate of packets forwarding :)

**Comment by sergey-dryabzhinsky** [comment]
That interesting. I really have such router.

**Comment by strizhechenko** [comment]
I think we can close this issue with wontfix)
